networks:
  bankSimplified:
    driver: bridge

services:
  
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bankSimplified
      POSTGRES_DB: bank
      POSTGRES_USER: root
      #volumes:
      # - migrations:/var/lib/postgresql/data/migrations
    networks:
      - bankSimplified
  
  bank_api:
    &api
    build: ../
    hostname: bank_api
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - bankSimplified
      
      
 
      
    