networks:
  bank:
    driver: bridge

services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bank_api_01
      - bank_api_02
      - bank_api_03
    networks:
       - bank
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: 60MB
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bankSimplified
      POSTGRES_DB: bank
      POSTGRES_USER: root
      #volumes:
      # - migrations:/var/lib/postgresql/data/migrations
    networks:
      - bank
    deploy:
      resources:
        limits:
          cpus: 0.7
          memory: 300MB
    
  bank_api_01:
    &bank_api
    build: ../
    hostname: bankApi01
    #ports:
      #- "8082:8080"
    depends_on:
      - db
    networks:
      - bank
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 150MB 
      
  bank_api_02:
    <<: *bank_api
    hostname: bankApi02
    #ports:
      #- "8083:8080"
  bank_api_03:
    <<: *bank_api
    hostname: bankApi03

      
 
      
    