networks:
  bankSimplified:
    driver: bridge

services:
  db:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: bankSimplified
      POSTGRES_DB: bank
      POSTGRES_USER: root
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - bankSimplified
